language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

install:
  - "pip install blist"
  - "pip install tabulate"
  - "pip install python-coveralls"
  - "pip install coverage"
  - "python setup.py install"

script:
   - coverage run --source raccoon -m py.test
   - coverage report -m

after_success:
  - coveralls
